sudo: required

addons:
    apt:
        update: true

os: linux

install: ./setup.sh

language: c

before_script:
    - autoreconf --install
    - configure --prefix=/usr --enable-benchmarks --enable-examples

script:
    - make clean
    - make
    - make check
    - sudo make install
