sudo: required

addons:
    apt:
        update: true

os:
    - linux
    - osx

jobs:
    include:
        - stage: build-c
          language: c
          install: ./setup.sh
          before_script:
            - autoreconf --install
            - pwd
            - ls
            - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --enable-benchmarks --enable-examples          ; fi
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix=/usr --enable-benchmarks --enable-examples          ; fi
          script:
            - make clean
            - make
        - stage: test-c
          language: c
          script:
            - make check
        - stage: deploy-c
          language: c
          script:
            - sudo make install
