sudo: required

addons:
    apt:
        update: true

os:
    - linux
    - osx

install: ./setup.sh

language: c

before_script:
    - autoreconf --install
    - pwd
    - ls
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --enable-benchmarks --enable-examples          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix=/usr --enable-benchmarks --enable-examples          ; fi

script:
    - make clean
    - make
    - make check
    - sudo make install
